on: [push, pull_request]

name: Build indices

jobs:
  build:
    name: Build indices
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_16
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set directories
      run: |
        echo "R_PKG_DIR=${R_HOME}/site-library" >> $GITHUB_ENV

    - name: Restore the package directory
      uses: actions/cache@v3
      with:
        path: ${{ env.R_PKG_DIR }}
        key: rpkg-20230203

    - name: Install dependencies
      shell: Rscript {0}
      run: BiocManager::install(c("jsonlite", "S4Vectors", "BiocFileCache", "AnnotationHub", "ensembldb"))

    - name: Restore the EnsDb directory
      uses: actions/cache@v3
      with:
        path: ensdb_cache
        key: ensdb-20230203

    - name: Restore the GMT directory
      uses: actions/cache@v3
      with:
        path: gmt_cache
        key: gmt-20230203

    - name: Build the indices
      run: R -f "build_index.R"

    - name: Create a release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: assets/*
